leftnav:
- identifier: 854f3bac-c767-714f-291d-3c4ac56f800b
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: cb64ea13-66ae-83d1-db8c-2b80c0d0aa8f
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 8bbd0df2-02ec-5150-a5d4-1d0325fbf268
  name: Instructor Insights
  pageRef: /pages/instructor-insights
  weight: 30
- identifier: 2caf59f2-852e-612c-3397-8a1337c5e75d
  name: Readings
  pageRef: /pages/readings
  weight: 40
- identifier: 198c70e4-7449-277a-24ba-73c0e33fa31f
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 50
- identifier: aaedd2b4-e120-7951-d190-318c0d25a9bd
  name: Audio Lectures
  pageRef: /video_galleries/audio-lectures
  weight: 60
- identifier: 4c06733e-ec6d-0da6-3a86-82ed555f2a34
  name: Assignments
  pageRef: /pages/assignments
  weight: 70
- identifier: 92c4f046-87ae-bed2-d1d2-1ba865a241b3
  name: Related Resources
  pageRef: /pages/related-resources
  weight: 80
